export interface DayDefinition {
  day_number: number;
  theme: string;
  title: string;
  quote: string;
  author: string;
  intro: string;
  action_prompt: string;
  reflection_prompt: string;
}

export const CHALLENGE_DAYS_DATA: DayDefinition[] = [
  {
    day_number: 1,
    theme: 'Opportunity',
    title: 'Recognizing The Doors Around You',
    quote: 'Opportunity often comes disguised in the form of misfortune, or temporary defeat.',
    author: 'Napoleon Hill',
    intro: 'Activation begins when you stop waiting for the perfect circumstances and start opening the doors right in front of you.',
    action_prompt: 'Identify one hidden opportunity in your current situation today and take the first concrete step toward it.',
    reflection_prompt: 'What doors have I been walking past because I was focused on past obstacles?',
  },
  {
    day_number: 2,
    theme: 'Action',
    title: 'Movement Over Intentions',
    quote: 'Action is the foundational key to all success.',
    author: 'Pablo Picasso',
    intro: 'Intention without execution is just hallucination. Today is dedicated to raw, unhesitating movement.',
    action_prompt: 'Complete one item on your to-do list that you have delayed for more than 48 hours.',
    reflection_prompt: 'Where in my life am I overthinking instead of taking physical action?',
  },
  {
    day_number: 3,
    theme: 'Courage',
    title: 'Facing The Friction',
    quote: 'Courage is resistance to fear, mastery of fear - not absence of fear.',
    author: 'Mark Twain',
    intro: 'Growth lives on the other side of uncomfortable conversations and scary choices.',
    action_prompt: 'Do one thing today that makes your heart beat slightly faster out of discomfort or fear.',
    reflection_prompt: 'What uncomfortable truth or task have I been avoiding out of fear of judgment or failure?',
  },
  {
    day_number: 4,
    theme: 'Discipline',
    title: 'Discipline Over Mood',
    quote: 'We must all suffer one of two pains: the pain of discipline or the pain of regret.',
    author: 'Jim Rohn',
    intro: 'Relying on motivation is amateur. Professionals execute regardless of how they feel in the moment.',
    action_prompt: 'Honor every single promise you make to yourself today, down to the exact minute.',
    reflection_prompt: 'Did I act today based on my goals or based on my temporary mood?',
  },
  {
    day_number: 5,
    theme: 'Purpose',
    title: 'Clarifying Your Why',
    quote: 'He who has a why to live can bear almost any how.',
    author: 'Friedrich Nietzsche',
    intro: 'Without a clear destination, any wind will blow you off course. Reconnect with your core mission.',
    action_prompt: 'Write down your primary 12-month goal in one sentence and read it aloud 3 times today.',
    reflection_prompt: 'Is my daily effort aligned with the person I am striving to become?',
  },
  {
    day_number: 6,
    theme: 'Self-Talk',
    title: 'Mastering The Inner Dialogue',
    quote: 'Whether you think you can, or you think you can’t – you’re right.',
    author: 'Henry Ford',
    intro: 'The most important conversation you will have today is the one happening inside your own mind.',
    action_prompt: 'Catch and replace every negative self-defeating thought today with a disciplined action statement.',
    reflection_prompt: 'What limiting narrative have I been repeatedly telling myself?',
  },
  {
    day_number: 7,
    theme: 'Learning',
    title: 'Continuous Elevation',
    quote: 'Live as if you were to die tomorrow. Learn as if you were to live forever.',
    author: 'Mahatma Gandhi',
    intro: 'Expand your mind deliberately. Every day must yield new knowledge that sharpens your edge.',
    action_prompt: 'Spend 20 focused minutes reading, studying, or listening to educational material in your field.',
    reflection_prompt: 'What critical skill or concept did I learn or sharpen today?',
  },
  {
    day_number: 8,
    theme: 'People',
    title: 'Elevating Your Inner Circle',
    quote: 'You are the average of the five people you spend the most time with.',
    author: 'Jim Rohn',
    intro: 'Your environment either fuels your activation or drains your energy. Choose your relationships intentionally.',
    action_prompt: 'Reach out to a high-standard peer or mentor and offer value or express genuine appreciation.',
    reflection_prompt: 'Do the people around me challenge me to rise or encourage me to settle?',
  },
  {
    day_number: 9,
    theme: 'Comfort Zone',
    title: 'Expanding Your Perimeter',
    quote: 'A ship in harbor is safe, but that is not what ships are built for.',
    author: 'John A. Shedd',
    intro: 'Comfort is the enemy of progress. Break out of your routine and embrace positive tension.',
    action_prompt: 'Take a cold shower or push your physical workout 15% beyond your normal stopping point.',
    reflection_prompt: 'How did pushing past my comfort zone expand my confidence today?',
  },
  {
    day_number: 10,
    theme: 'Execution',
    title: 'Relentless Completion',
    quote: 'Ideas are easy. Execution is everything.',
    author: 'John Doerr',
    intro: 'Finish what you start. Today is about closing open loops and crossing the finish line on tasks.',
    action_prompt: 'Pick one unfinished project and work on it until it is 100% complete.',
    reflection_prompt: 'What open loops am I dragging along, and how did closing one release my mental energy?',
  },
  {
    day_number: 11,
    theme: 'Energy',
    title: 'Optimizing Vitality',
    quote: 'Energy is the essence of life. Every day you decide how you are going to use it.',
    author: 'Oprah Winfrey',
    intro: 'High output requires high energy. Manage your sleep, nutrition, and physical movement with precision.',
    action_prompt: 'Drink 3 liters of water today and eliminate processed sugars or junk food entirely.',
    reflection_prompt: 'What habits or inputs drained my physical and mental vitality today?',
  },
  {
    day_number: 12,
    theme: 'Focus',
    title: 'Eliminating Distractions',
    quote: 'Concentrate all your thoughts upon the work at hand.',
    author: 'Alexander Graham Bell',
    intro: 'Multi-tasking is a myth. Deep, uninterrupted focus is the superpower of modern execution.',
    action_prompt: 'Perform a 90-minute deep work block with your phone in another room or on Do Not Disturb.',
    reflection_prompt: 'How much higher was my output when I guarded my attention against distractions?',
  },
  {
    day_number: 13,
    theme: 'Fear',
    title: 'Dismantling Illusion',
    quote: 'Do the thing you fear most and the death of fear is certain.',
    author: 'Mark Twain',
    intro: 'Fear is just false evidence appearing real. Walk straight through it.',
    action_prompt: 'Initiate the one task or phone call you have been dreading all week.',
    reflection_prompt: 'Was the feared event as catastrophic as my mind imagined it to be?',
  },
  {
    day_number: 14,
    theme: 'Health',
    title: 'The Physical Foundation',
    quote: 'To enjoy the glow of good health, you must exercise.',
    author: 'Gene Tunney',
    intro: 'Your body is the vessel for your purpose. Train it with respect and intensity.',
    action_prompt: 'Engage in at least 45 minutes of intentional physical exercise today.',
    reflection_prompt: 'How did physical exertion clear my mental fog and elevate my mood?',
  },
  {
    day_number: 15,
    theme: 'Creation',
    title: 'Producing Over Consuming',
    quote: 'Creativity is intelligence having fun.',
    author: 'Albert Einstein',
    intro: 'Shift from being a passive consumer of other people’s content to a builder of your own value.',
    action_prompt: 'Create something original today: write an article, build a component, or design a solution.',
    reflection_prompt: 'Did I spend more hours creating value today or consuming noise?',
  },
  {
    day_number: 16,
    theme: 'Communication',
    title: 'Clarity & Conviction',
    quote: 'The single biggest problem in communication is the illusion that it has taken place.',
    author: 'George Bernard Shaw',
    intro: 'Speak with intention, listen with empathy, and state your standards clearly.',
    action_prompt: 'Have a clear, direct conversation with someone where you express your expectations without ambiguity.',
    reflection_prompt: 'Where was I vague in my communication today, and how can I express myself more clearly?',
  },
  {
    day_number: 17,
    theme: 'Standards',
    title: 'Refusal To Compromise',
    quote: 'If you don’t stand for something, you will fall for anything.',
    author: 'Gordon A. Eadie',
    intro: 'Your life does not get better by chance; it gets better by elevating your baseline standards.',
    action_prompt: 'Identify one low-standard habit you currently tolerate and eliminate it for the rest of today.',
    reflection_prompt: 'What new standard did I establish for myself today?',
  },
  {
    day_number: 18,
    theme: 'Gratitude',
    title: 'Grounded Appreciation',
    quote: 'Gratitude turns what we have into enough.',
    author: 'Aesop',
    intro: 'Gratitude is not passive sentimentality; it is a tactical anchor for resilience.',
    action_prompt: 'Write down 5 specific, non-obvious things you are grateful for today and why.',
    reflection_prompt: 'How does appreciating my current blessings fuel my drive for future growth?',
  },
  {
    day_number: 19,
    theme: 'Leadership',
    title: 'Leading By Example',
    quote: 'Leadership is not about a title or a designation. It’s about impact, influence and inspiration.',
    author: 'Robin Sharma',
    intro: 'Before you can lead others, you must demonstrate total command over your own habits.',
    action_prompt: 'Step up and solve a problem for someone else without being asked to do so.',
    reflection_prompt: 'Did my actions today set an example worth following?',
  },
  {
    day_number: 20,
    theme: 'Time',
    title: 'Guarding Your Currency',
    quote: 'Time is what we want most, but what we use worst.',
    author: 'William Penn',
    intro: 'Time is non-renewable. Audit your minutes with the same scrutiny you audit your finances.',
    action_prompt: 'Track every 30-minute block of your day and categorize it as Productive, Rest, or Wasted.',
    reflection_prompt: 'Where did I leak precious time today, and how will I eliminate that leak tomorrow?',
  },
  {
    day_number: 21,
    theme: 'Persistence',
    title: 'Outlasting The Resistance',
    quote: 'Energy and persistence conquer all things.',
    author: 'Benjamin Franklin',
    intro: 'The threshold of 21 days marks a profound shift in habit formation. Stay relentless.',
    action_prompt: 'When you feel like stopping or relaxing today, push for an extra 15 minutes of work.',
    reflection_prompt: 'How did my refusal to quit when tired build my mental fortitude?',
  },
  {
    day_number: 22,
    theme: 'Relationships',
    title: 'Nurturing Key Bonds',
    quote: 'Deep relationships are the true wealth of human existence.',
    author: 'Workbook Insight',
    intro: 'Success at the expense of meaningful human connection is ultimate failure. Invest in your people.',
    action_prompt: 'Spend 30 minutes of 100% undivided, phone-free time with someone you love or care about.',
    reflection_prompt: 'Did I show up fully for the people who matter most in my life today?',
  },
  {
    day_number: 23,
    theme: 'Identity',
    title: 'Becoming The Activator',
    quote: 'You do not rise to the level of your goals. You fall to the level of your systems.',
    author: 'James Clear',
    intro: 'Behavior follows identity. Stop saying "I am trying" and start saying "This is who I am."',
    action_prompt: 'Write down 3 identity statements starting with "I am..." that define your activated self.',
    reflection_prompt: 'Did my actions today reflect the identity of a disciplined, activated leader?',
  },
  {
    day_number: 24,
    theme: 'Opportunity',
    title: 'Compounding Openings',
    quote: 'Small opportunities are often the beginning of great enterprises.',
    author: 'Demosthenes',
    intro: 'Revisiting opportunity with 23 days of momentum gives you a sharper lens for high-value leverage.',
    action_prompt: 'Look at a challenge in your work or life and find the strategic advantage hidden within it.',
    reflection_prompt: 'What new opportunity became visible only after I built 3 weeks of momentum?',
  },
  {
    day_number: 25,
    theme: 'Courage',
    title: 'Bold Execution',
    quote: 'Fortune favors the bold.',
    author: 'Virgil',
    intro: 'Courage at Day 25 is about making bold commitments that propel you into your next level.',
    action_prompt: 'Make one bold decision today that you have been hesitating on for weeks.',
    reflection_prompt: 'How did taking a bold leap today shift my momentum forward?',
  },
  {
    day_number: 26,
    theme: 'Results',
    title: 'Measuring Real Output',
    quote: 'Don’t mistake activity with achievement.',
    author: 'John Wooden',
    intro: 'Being busy is not the same as producing results. Measure what actually moves the needle.',
    action_prompt: 'Evaluate your top 3 projects and measure concrete output instead of hours spent.',
    reflection_prompt: 'Did I achieve tangible results today, or did I merely engage in busywork?',
  },
  {
    day_number: 27,
    theme: 'Reflection',
    title: 'Honest Self-Audit',
    quote: 'Without proper self-evaluation, failure is inevitable.',
    author: 'John C. Maxwell',
    intro: 'Reflect with ruthless honesty on your progress over the past 27 days of activation.',
    action_prompt: 'Review your notes from Day 01 to today and write a 3-paragraph summary of your growth.',
    reflection_prompt: 'What is the biggest transformation I have noticed in my mindset and discipline since Day 01?',
  },
  {
    day_number: 28,
    theme: 'Service',
    title: 'Contributing Beyond Yourself',
    quote: 'The best way to find yourself is to lose yourself in the service of others.',
    author: 'Mahatma Gandhi',
    intro: 'True personal activation expands outward into service and impact on others.',
    action_prompt: 'Perform an act of service, mentorship, or unexpected kindness without seeking recognition.',
    reflection_prompt: 'How did focusing on serving others elevate my sense of purpose today?',
  },
  {
    day_number: 29,
    theme: 'Vision',
    title: 'The Next Horizon',
    quote: 'The future belongs to those who prepare for it today.',
    author: 'Malcolm X',
    intro: 'As you near the completion of the 30 days, cast your vision for the next chapter of your life.',
    action_prompt: 'Outline your vision for the next 90 days after completing this activation challenge.',
    reflection_prompt: 'What major goals will I tackle next using the discipline I built here?',
  },
  {
    day_number: 30,
    theme: 'Activation',
    title: 'Full System Activation',
    quote: 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.',
    author: 'Will Durant',
    intro: 'Day 30 is not the end; it is the activation of a permanent, disciplined lifestyle.',
    action_prompt: 'Complete your 30-Day Final Review and make your next long-term commitment.',
    reflection_prompt: 'I am activated. What legacy will I build from this day forward?',
  },
];

export function getDayDefinition(dayNumber: number): DayDefinition {
  const found = CHALLENGE_DAYS_DATA.find((d) => d.day_number === dayNumber);
  if (found) return found;
  return CHALLENGE_DAYS_DATA[0];
}
